version: "3.8"
services:
    beers:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        networks:
            - default
    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: beers-app
            MYSQL_USER: beers-app
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./../docker-volumes/beers-app/db:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: beers-app
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        networks:
            - default
networks:
    default:
        external: false
        driver: bridge

